# Generated by Django 2.2.3 on 2019-07-21 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['created']},
        ),
    ]
